# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
  branches:
    master:
    - step:
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                    SSH_USER: $SSH_USER
                    SERVER: $SSH_SERVER
                    COMMAND: '/home/demo/deploy_config/yamaha/developer.sh'
